name: Auto Commit

permissions:
  contents: write

on:
  schedule:
    - cron: '10 13 * * *'  # Runs daily at 6:40 PM IST (1:10 PM UTC)
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (master branch)
        uses: actions/checkout@v3
        with:
          ref: master  # ✅ Checkout master branch

      - name: Make changes
        run: |
          echo "🕒 Auto commit on $(date)" >> commit-log.txt

      - name: Commit changes
        run: |
          git config --global user.name "saketkumar28"
          git config --global user.email "kumarsaket2801@gmail.com"  # Replace this
          git add commit-log.txt || echo "Nothing to add"
          git diff --staged --quiet || git commit -m "✅ Daily auto commit"
          git push origin master  # ✅ Push to master
