name: Auto Commit

permissions:
  contents: write

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make changes
        run: |
          echo "🕒 Auto commit on $(date)" >> commit-log.txt

      - name: Commit changes
        run: |
          git config --global user.name "Saket Kumar"
          git config --global user.email "youremail@example.com"
          git add commit-log.txt || echo "Nothing to add"
          git diff --staged --quiet || git commit -m "✅ Daily auto commit"
          git push
